
package com.ektec.modelo.redeban;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompraElectronica_MsgSetPortType", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompraElectronicaMsgSetPortType {


    /**
     * 
     * @param compraProcesarSolicitud
     * @return
     *     returns wsclient.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraProcesarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraProcesarRespuesta")
    public TipoRespuesta compraProcesar(
        @WebParam(name = "compraProcesarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraProcesarSolicitud")
        TipoSolicitudCompra compraProcesarSolicitud);

    /**
     * 
     * @param compraReversarSolicitud
     * @return
     *     returns wsclient.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraReversarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraReversarRespuesta")
    public TipoRespuesta compraReversar(
        @WebParam(name = "compraReversarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraReversarSolicitud")
        TipoSolicitudCompra compraReversarSolicitud);

}
