
package com.ektec.modelo.redeban;

import com.ektec.utilidades.Utilidades;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompraElectronica_HTTP_Service", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
public class CompraElectronicaHTTPService
    extends Service
{

    private final static URL COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
    private final static QName COMPRAELECTRONICAHTTPSERVICE_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:" + new File("").getAbsolutePath() + Utilidades.getPropiedadConfig("servicio.getPaid.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION = url;
        COMPRAELECTRONICAHTTPSERVICE_EXCEPTION = e;
    }

    public CompraElectronicaHTTPService() {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort() {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Port"), CompraElectronicaMsgSetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Port"), CompraElectronicaMsgSetPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPRAELECTRONICAHTTPSERVICE_EXCEPTION!= null) {
            throw COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
        }
        return COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    }

}
