
package com.ektec.modelo.redeban;

import com.ektec.utilidades.Utilidades;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CompraElectronica_HTTP_Service")
public class CompraElectronicaHTTPService
        extends Service {

    private final static URL COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
    private final static QName COMPRAELECTRONICAHTTPSERVICE_QNAME = new QName("servicio.getPaid.url", "CompraElectronica_HTTP_Service");
    private final static QName COMPRAELECTRONICAPORT_QNAME = new QName(Utilidades.getPropiedadConfig("servicio.getPaid.url"), "CompraElectronica_HTTP_Port");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:" + new File("").getAbsolutePath() + Utilidades.getPropiedadConfig("servicio.getPaid.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION = url;
        COMPRAELECTRONICAHTTPSERVICE_EXCEPTION = e;
    }

    public CompraElectronicaHTTPService() {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort() {
        return super.getPort(COMPRAELECTRONICAPORT_QNAME, CompraElectronicaMsgSetPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort(WebServiceFeature... features) {
        return super.getPort(COMPRAELECTRONICAPORT_QNAME, CompraElectronicaMsgSetPortType.class, features);
    }

    @org.jetbrains.annotations.Contract(pure = true)
    private static URL __getWsdlLocation() {
        if (COMPRAELECTRONICAHTTPSERVICE_EXCEPTION != null) {
            throw COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
        }
        return COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    }

}
